---
title: "Methods"
author: "Emma Dann"
date: "06/08/2020"
output: html_document
---

## Quasi-likelihood negative bionomial GLM from edgeR

<!-- For neighbourhood $n$ with counts $y_{ns}$ for each sample $s$, the counts are modelled as a quasi-negative binomial distribution with mean $\mu_{ns}$ with a generalized linear model. This means that we allow for overdispersion of the counts data. -->

<!-- With a log-link GLM with G coefficients (which represent groups) the mean is -->
<!-- $$ -->
<!-- log\ \mu_{ns} = \sum_{g=1}^{G}x_{sg}\beta_{ng} + o_{ns} -->
<!-- $$ -->
<!-- Here $\beta_{ng}$ is the neighbourhood-specific value of coefficient $g$ i.e. the log-transformed average proportion of cells within a group. $x_{sg}$ specifies the group to which each sample belongs. $o_{ns}$ is the offset, representing the log-transformed total number of cells, that insures that differences in the numbers of cells between groups do not cause differences in $\beta_{ng}$. -->

<!-- ---  -->

For neighbourhood $n$ with counts $y_{ns}$ for each sample $s$, the counts are best modelled by the NB distribution, as it is supported over all non-negative integers and can accurately model both small and large cell counts. For such non-normally distributed data we use generalized-linear models (GLMs) as an extension of classic linear models that can accomodate complex experimental designs. We therefore assume that 
$$
y_{ns} \sim NB(\mu_{ns},\phi_{n}),
$$
where $\mu_{ns}$ is the mean and $\phi_{n}$ is the NB dispersion parameter. 
The expected count value for a neighbourhood in a sample $\mu_{ns}$ is given by 
$$
\mu_{ns} = \lambda_{ns}N_s
$$

where $\lambda_{ns}$ is the proportion of cells belonging to sample $s$ in $n$ and $N_s$ is the total number of cells of $s$. In practice, $\lambda_{ns}$ represents the biological variability that can be affected by treatment condition, age or any biological covariate of interest. We use a log-linear model to represent the influence of the biological condition on the expected counts in neighbourhoods:
$$
log\ \mu_{ns} = \sum_{g=1}^{G}x_{sg}\beta_{ng} + log\ N_s
$$
where $x_sg$ is the covariate vector indicating the condition applied to sample $s$ (i.e. $x_{sg}$ is an element of the design matrix), $\beta_{ng}$ is the regression coefficient by which the covariate effects are mediated for neighbourhood $n$. 

Estimation of $\beta_{ng}$ for each $n$ and $g$ is performed by fitting the GLM to the count data for each neighbourhood, i.e. by estimating the dispersion $\phi_{n}$ that models the variability of cell counts for replicate samples for each neighbourhood. Dispersion estimation is done using the quasi-likelihood method in `edgeR`, where the dispersion is modelled from the GLM deviance and stabilized with empirical Bayes shrinkage, to stabilize the estimates in the presence of limited replication. 

## Adaptation of Cydar spatial FDR to neighbourhoods

The spatial FDR can be intrpreted as the proportion of the union of neighbourhoods that is occupied by false-positive neighbourhoods. This adjusts for the fact that some neighbourhoods are more densely connected than others. To control spatial FDR in the KNN graph, we apply a weighted version of the Benjamini-Hochberg (BH) method. Briefly, to control for FDR at some threshold $\alpha$ we reject null hypothesis $i$ where the associated p-value is less than the threshold
$$
\max_i{p_{(i)}: p_{(i)}\le \alpha\frac{\sum_{l=1}^{i}w_{(l)}}{\sum_{l=1}^{n}w_{(l)}}}
$$
Where the weight $w_{(i)}$ is the reciprocal of the neighbourhood connectivity $c_n$.

We tested different options as measures of neighbourhood connectivity, namely:

- edge connectivity: the minimum number of edges whose deletion from a graph $G$ disconnects $G$
- vertex connectivity: the minimum number of vertices whose deletion from a graph $G$ disconnects $G$
- k-distance: the distance to the kth nearest neighbour of the index vertex (the vertex sampled to define the neighbourhood)
- neighbour-distance: the average euclidean distance of points within a neighbourhood




