---
title: "Milo w complex design"
output: html_notebook
---


```{r}
library(miloR)
library(SingleCellExperiment)
library(tidyverse)

# BiocManager::install("MouseGastrulationData")
library(MouseGastrulationData)
```

## Load gastrulation atlas data

```{r}
embryo_sce <- EmbryoAtlasData(type="processed")
```

```{r}
embryo_milo_mnn
```

## Preprocessing
```{r}
logcounts(embryo_sce) <- log1p(counts(embryo_sce))

dec <- scran::modelGeneVar(embryo_sce)
hvgs <- scran::getTopHVGs(dec, n=5000)

embryo_sce <- scater::runPCA(embryo_sce, subset_row=hvgs)
```


## Build KNN graphs 
For corrected and uncorrected data

```{r}
## Milo obj for corrected data
embryo_milo_mnn <- Milo(embryo_sce)
reducedDim(embryo_milo_mnn, "PCA") <- reducedDim(embryo_milo_mnn, "pca.corrected")
# Remove NA lines in the PCA (not sure what these guys are)
embryo_milo_mnn <- embryo_milo_mnn[,apply(reducedDim(embryo_milo_mnn, "PCA"),1, function(x) !all(is.na(x)))]

## Milo obj for uncorrected data
embryo_milo_uncor <- Milo(embryo_sce)

## Build KNNs
embryo_milo_mnn <- buildGraph(embryo_milo_mnn, k = 30, d=30)
embryo_milo_uncor <- buildGraph(embryo_milo_uncor, k = 30, d=30)

embryo_milo_uncor <- scater::runUMAP(embryo_milo_uncor, pca=30, dimred="PCA")
```

```{r, fig.height=10, fig.width=10}
scater::plotReducedDim(embryo_milo_uncor, dimred = "UMAP", colour_by = "stage") 
scater::plotReducedDim(embryo_milo_mnn, dimred = "umap", colour_by = "stage") 

```
```{r, fig.width=10, fig.height=10}
stage_order <- c("E6.5", "E6.75", "E7.0", "E7.25",  "mixed_gastrulation", "E7.5", "E7.75", "E8.0", "E8.25", "E8.5")

make_umap_df <- function(embryo_milo_mnn, dimred){
  umap_df <- data.frame(reducedDim(embryo_milo_mnn, dimred))
  colnames(umap_df) <- c("UMAP1", "UMAP2")
  
  df <- cbind(umap_df, data.frame(colData(embryo_milo_mnn)[c("stage", "sequencing.batch")])) %>%
    mutate(stage=factor(stage, levels = stage_order),
           sequencing.batch = factor(sequencing.batch)) %>%
    mutate(stage=as.numeric(stage))
  df  
}

uncor_1 <- ggplot(make_umap_df(embryo_milo_uncor, "UMAP"), aes(UMAP1, UMAP2, color=stage)) +
  geom_point(size=0.1, alpha=0.1) +
  scale_color_viridis(option='magma', name="Time point") +
  theme_classic(base_size = 14) +
  theme(axis.text = element_blank(), axis.ticks = element_blank(),
        legend.background = element_blank(),
        legend.position = "top", plot.title=element_text(hjust=0.5)) 

uncor_2 <-
  ggplot(make_umap_df(embryo_milo_uncor, "UMAP"), aes(UMAP1, UMAP2, color=sequencing.batch)) +
  geom_point(size=0.1, alpha=0.7) +
  scale_color_brewer(palette="Set2", name="Seq. batch") +
  guides(color=guide_legend(override.aes = list(size=2))) +
  theme_classic(base_size = 14) +
  theme(axis.text = element_blank(), axis.ticks = element_blank(),
        legend.background = element_blank(),
        legend.position = "top", plot.title=element_text(hjust=0.5)) 


mnn_1 <- ggplot(make_umap_df(embryo_milo_mnn, "umap"), aes(UMAP1, UMAP2, color=stage)) +
  geom_point(size=0.1, alpha=0.1) +
  scale_color_viridis(option='magma', name="time_point") +
  theme_classic(base_size = 14) +
  theme(axis.text = element_blank(), axis.ticks = element_blank(),
        legend.background = element_blank(),
        legend.position = "top", plot.title=element_text(hjust=0.5)) 

mnn_2 <-
  ggplot(make_umap_df(embryo_milo_mnn, "umap"), aes(UMAP1, UMAP2, color=sequencing.batch)) +
  geom_point(size=0.1, alpha=0.7) +
  scale_color_brewer(palette="Set2", name="Seq. batch") +
  guides(color=guide_legend(override.aes = list(size=2))) +
  theme_classic(base_size = 14) +
  theme(axis.text = element_blank(), axis.ticks = element_blank(),
        legend.background = element_blank(),
        legend.position = "top", plot.title=element_text(hjust=0.5)) 

((uncor_2  + uncor_1) / ((mnn_2 + guides(color="none")) + (mnn_1 + guides(color="none")))) +
  ggsave("~/milo_output/batch_effect_mouse_umaps.png", width = 7, height = 7)
```

```{r, fig.height=14, fig.width=14}
scater::plotReducedDim(embryo_milo_uncor, dimred = "UMAP", colour_by = "sample")
scater::plotReducedDim(embryo_milo_uncor, dimred = "UMAP", colour_by = "stage")

scater::plotReducedDim(embryo_milo_mnn, dimred = "umap", colour_by = 'sample') 
scater::plotReducedDim(embryo_milo_mnn, dimred = "umap", colour_by = 'stage') 

```
```{r, fig.height=14, fig.width=14}
scater::plotReducedDim(embryo_milo_uncor, dimred = "UMAP", colour_by = "sequencing.batch")
scater::plotReducedDim(embryo_milo_mnn, dimred = "umap", colour_by = "sequencing.batch")

scater::plotReducedDim(embryo_milo_uncor, dimred = "UMAP", colour_by = "pool")
scater::plotReducedDim(embryo_milo_mnn, dimred = "umap", colour_by = "pool")
```

## Make neighbourhoods

```{r}
embryo_milo_mnn <- makeNhoods(embryo_milo_mnn)
embryo_milo_uncor <- makeNhoods(embryo_milo_uncor)

plotNhoodSizeHist(embryo_milo_mnn)
plotNhoodSizeHist(embryo_milo_uncor)
```

```{r}
embryo_milo_mnn <- countCells(embryo_milo_mnn, meta.data = data.frame(colData(embryo_milo_mnn)), sample="sample")
embryo_milo_uncor <- countCells(embryo_milo_uncor, meta.data = data.frame(colData(embryo_milo_uncor)), sample="sample")
```

Make design matrix

```{r}
embryo_design <- data.frame(colData(embryo_milo_mnn))[,c("sample", "stage", "sequencing.batch", "pool")]
embryo_design <- distinct(embryo_design)
rownames(embryo_design) <- NULL

stage_order <- c("E6.5", "E6.75", "E7.0", "E7.25",  "mixed_gastrulation", "E7.5", "E7.75", "E8.0", "E8.25", "E8.5")

embryo_design <- mutate(embryo_design, stage = factor(stage, levels = stage_order, ordered = TRUE))
embryo_design <- mutate(embryo_design, stage_int = as.numeric(stage))
embryo_design <- mutate(embryo_design, sequencing.batch = as.factor(sequencing.batch))
# embryo_design <- mutate(embryo_design, batch = str_c(sequencing.batch, "_", stage))
# embryo_design <- mutate(embryo_design, stage_int = ifelse(stage=="mixed_gastrulation", NA, as.numeric(stage)))
embryo_design <- embryo_design %>%
  column_to_rownames("sample")
embryo_design
```

```{r}
embryo_milo_mnn <- calcNhoodDistance(embryo_milo_mnn, d=30, reduced.dim = "PCA")
embryo_milo_uncor <- calcNhoodDistance(embryo_milo_uncor, d=30, reduced.dim = "PCA")
```

Try doing DA analysis with or without including the technical covariate in the design

```{r}
da_mnn_stage <- testNhoods(embryo_milo_mnn, design = ~ stage_int, design.df = embryo_design)
da_mnn_batch <- testNhoods(embryo_milo_mnn, design = ~ sequencing.batch, design.df = embryo_design)
da_mnn_stage_batch <- testNhoods(embryo_milo_mnn, design = ~ sequencing.batch + stage_int, design.df = embryo_design)

da_uncor_stage <- testNhoods(embryo_milo_uncor, design = ~ stage_int, design.df = embryo_design)
da_uncor_batch <- testNhoods(embryo_milo_uncor, design = ~ sequencing.batch, design.df = embryo_design)
da_uncor_stage_batch <- testNhoods(embryo_milo_uncor, design = ~ sequencing.batch + stage_int, design.df = embryo_design)
```

Diagnostic plots

```{r, fig.height=5, fig.width=10}
ggplot(da_mnn_stage, aes(SpatialFDR)) + geom_histogram() +
ggplot(da_mnn_stage, aes(logFC, -log10(SpatialFDR))) + geom_point()

ggplot(da_mnn_stage_batch, aes(SpatialFDR)) + geom_histogram() +
ggplot(da_mnn_stage_batch, aes(logFC, -log10(SpatialFDR))) +
  geom_point()

ggplot(da_uncor_stage, aes(SpatialFDR)) + geom_histogram() +
ggplot(da_uncor_stage, aes(logFC, -log10(SpatialFDR))) +
  geom_point()

ggplot(da_uncor_stage_batch, aes(SpatialFDR)) + geom_histogram() +
ggplot(da_uncor_stage_batch, aes(logFC, -log10(SpatialFDR))) +
  geom_point()


```


```{r}
bind_rows(mutate(da_mnn_stage, design="stage"),
          mutate(da_mnn_stage_batch, design="stage_batch"),
          
          ) %>%
  dplyr::select(Nhood, design, SpatialFDR) %>%
  mutate(predicted_outcome = ifelse(SpatialFDR < 0.1, 'is DA', "not DA")) %>%
  pivot_wider(id_cols=c("Nhood"), names_from="design", values_from="predicted_outcome") %>%
  group_by(stage, stage_batch) %>%
  summarise(n=n()) %>%
  ggplot(aes(stage, stage_batch)) +
  geom_tile(aes(fill=n)) +
  geom_text(aes(label=n)) +
  coord_fixed() +
  ylab("~ Seq. batch + Time point") +
  xlab("~ Time point") +
  scale_fill_gradient(low="grey98", high="red", name="# neighbourhoods") +
  theme_classic(base_size = 15) 

bind_rows(mutate(da_mnn_stage, design="stage"),
          mutate(da_mnn_batch, design="batch"),
          
          ) %>%
  dplyr::select(Nhood, design, SpatialFDR) %>%
  mutate(predicted_outcome = ifelse(SpatialFDR < 0.1, 'is DA', "not DA")) %>%
  pivot_wider(id_cols=c("Nhood"), names_from="design", values_from="predicted_outcome") %>%
  group_by(stage, batch) %>%
  summarise(n=n()) %>%
  ggplot(aes(stage, batch)) +
  geom_tile(aes(fill=n)) +
  geom_text(aes(label=n)) +
  coord_fixed() +
  ylab("~ Seq. batch") +
  xlab("~ Time point") +
  scale_fill_gradient(low="grey98", high="red", name="# neighbourhoods") +
  theme_classic(base_size = 15) 
  

bind_rows(mutate(da_uncor_stage, design="stage"),
          mutate(da_uncor_stage_batch, design="stage_batch")) %>%
  select(Nhood, design, SpatialFDR) %>%
  pivot_wider(id_cols=c("Nhood"), names_from="design", values_from="SpatialFDR") %>%
  ggplot(aes(-log10(stage), -log10(stage_batch))) +
  geom_point(alpha=0.5, size=0.5) +
  geom_hline(yintercept = -log10(0.01)) +
  geom_vline(xintercept = -log10(0.01)) +
  geom_abline() +
  coord_fixed() +
  ggtitle("uncorrected")
```
```{r}
bind_rows(mutate(da_mnn_stage, design="stage"),
          mutate(da_mnn_stage_batch, design="stage_batch")) %>%
  dplyr::select(Nhood, design, logFC) %>%
  pivot_wider(id_cols=c("Nhood"), names_from="design", values_from="logFC") %>%
  ggplot(aes(stage, stage_batch)) +
  geom_point(alpha=0.5, size=0.5) +
  # geom_vline(xintercept = -log10(0.05)) +
  # geom_hline(yintercept = -log10(0.05)) +
  ggtitle("corrected")

bind_rows(mutate(da_uncor_stage, design="stage"),
          mutate(da_uncor_stage_batch, design="stage_batch")) %>%
  dplyr::select(Nhood, design, logFC, SpatialFDR) %>%
  pivot_wider(id_cols=c("Nhood"), names_from="design", values_from=c("logFC", "SpatialFDR")) %>%
  mutate(color = case_when(SpatialFDR_stage_batch < 0.01 & SpatialFDR_stage < 0.01 ~ "signif_in_both",
                         SpatialFDR_stage_batch < 0.01 & SpatialFDR_stage > 0.01 ~ "signif_in_stage_batch",
                         SpatialFDR_stage_batch > 0.01 & SpatialFDR_stage < 0.01 ~ "signif_in_stage"
                         )) %>%
  ggplot(aes(logFC_stage, logFC_stage_batch, color=color)) +
  geom_point(alpha=0.5, size=0.5) +
  # geom_hline(yintercept = -log10(0.05)) +
  # geom_vline(xintercept = -log10(0.05)) +
  ggtitle("uncorrected")
```
```{r}
bind_rows(mutate(da_mnn_stage, design="~ Time point", correction="MNN corrected"),
          mutate(da_mnn_stage_batch, design="~ Seq. batch + Time point", correction="MNN corrected"),
          mutate(da_mnn_batch, design="~ Seq. batch", correction="MNN corrected"),
          mutate(da_uncor_stage, design="~ Time point", correction="Uncorrected"),
          mutate(da_uncor_stage_batch, design="~ Seq. batch + Time point", correction="Uncorrected"),
          mutate(da_uncor_batch, design="~ Seq. batch",correction="Uncorrected"),
          ) %>%
  mutate(design=factor(design, levels=rev(c("~ Seq. batch", "~ Time point", "~ Seq. batch + Time point")))) %>%
  mutate(correction=factor(correction, levels=c('Uncorrected', "MNN corrected"))) %>%
  mutate(is_signif=SpatialFDR < 0.01) %>%
  group_by(correction, design, is_signif) %>%
  summarise(n=n()) %>%
  group_by(correction, design) %>%
  mutate(frac=n*100/sum(n)) %>%
  ungroup() %>%
  mutate(class=paste(correction, design)) %>%
  ggplot(aes(design, frac)) +
  geom_col(data=. %>% dplyr::filter(!is_signif), aes(y=100)) +
  geom_col(data=. %>% dplyr::filter(is_signif),  aes(fill="is DA (FDR 10%)")) +
  geom_text(data=. %>% dplyr::filter(is_signif),
            aes(y=frac/2, label=n)
              ) +
  coord_flip() +
  xlab("DA test design") +
  ylab("% Neighbourhoods ") +
  facet_grid(correction ~.) +
  scale_fill_manual(values=brewer.pal(6,'Reds')[5], name="") +
  theme_classic(base_size = 14) +
  theme(legend.position="top") +
  ggsave("~/milo_output/batch_effect_mouse_DA.pdf", height = 4, width = 6)
```

```{r}

bind_rows(mutate(da_mnn_stage, design="stage", correction="MNN", 
                 nhood_size=sapply(nhoods(embryo_milo_mnn), function(x) length(x))),
          mutate(da_mnn_stage_batch, design="stage_batch", correction="MNN",
                 nhood_size=sapply(nhoods(embryo_milo_mnn), function(x) length(x))),
          mutate(da_uncor_stage, design="stage", correction="uncor",
                 nhood_size=sapply(nhoods(embryo_milo_uncor), function(x) length(x))),
          mutate(da_uncor_stage_batch, design="stage_batch", correction="uncor",
                 nhood_size=sapply(nhoods(embryo_milo_uncor), function(x) length(x))),
          ) %>%
  mutate(is_signif=SpatialFDR < 0.01) %>%
  mutate(class=paste(correction, design)) %>%
  group_by(class) %>%
  mutate(rank_logFC=rank(logFC)) %>%
  ggplot(aes(nhood_size, -log10(SpatialFDR), color=class)) +
  # ggplot(aes(nhood_size, abs(logFC), color=class)) + 
  geom_point(size=0.1) +
  facet_wrap(class~., scales="free_x")
```

Save objects 
```{r}
saveRDS(embryo_milo_mnn, "~/EmbryoAtlas_MNN_milo.RDS")
saveRDS(embryo_milo_uncor, "~/EmbryoAtlas_uncorrected_milo.RDS")
```

```{r}
embryo_milo_mnn <- readRDS("~/EmbryoAtlas_MNN_milo.RDS")
embryo_milo_uncor <- readRDS("~/EmbryoAtlas_uncorrected_milo.RDS")
```
```{r}
embryo_milo_mnn2 <- as(embryo_milo_mnn, "SingleCellExperiment")
embryo_milo_mnn2 <- Milo(embryo_milo_mnn2)
nhoods(embryo_milo_mnn2) <- nhoods(embryo_milo_mnn)
nhoodCounts(embryo_milo_mnn2) <- nhoodCounts(embryo_milo_mnn)
nhoodGraph(embryo_milo_mnn2) <- nhoodGraph(embryo_milo_mnn)
nhoodIndex(embryo_milo_mnn2) <- nhoodIndex(embryo_milo_mnn)
nhoodDistances(embryo_milo_mnn2) <- nhoodDistances(embryo_milo_mnn)
```

<!-- ### Downstream analysis of results -->

<!-- Using best batch correction setup -->
<!-- ```{r, fig.height=10, fig.width=10} -->
<!-- da_mnn_stage_batch <- annotateNhoods(embryo_milo_mnn, da_mnn_stage_batch, coldata_col = "celltype") -->
<!-- plotDAbeeswarm(da_mnn_stage_batch, group.by = "celltype") -->
<!-- ``` -->
<!-- ```{r} -->
<!-- embryo_milo_mnn <- buildNhoodGraph(embryo_milo_mnn, overlap=100) -->
<!-- ``` -->





<!-- Visualize DA neighbourhoods -->
<!-- ```{r} -->
<!-- embryo_milo_mnn <- buildNhoodGraph(embryo_milo_mnn) -->
<!-- embryo_milo_uncor <- buildNhoodGraph(embryo_milo_uncor) -->
<!-- ``` -->



